<a href="https://colab.research.google.com/github/Jonata-Garcia/Guia_Didatico_Python/blob/main/Do_B%C3%A1sico_ao_Avan%C3%A7ado_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
L=[1,2,3,4]
print (L)
print(L[0])
print(L[1])
print(L[2])
print(L[3])

print(len(L))



[1, 2, 3, 4]
1
2
3
4
4
10
40
100


In [ ]:
J = [10,20,30,40]
print(min(J))
print(max(J))
print(sum(J))
J.append(100)
print(J)
del J[0]
print(J)


10
40
100
[10, 20, 30, 40, 100]
[20, 30, 40, 100]


In [ ]:
R = [3,5,2,4,1,0]
R.sort()
print(R)

[0, 1, 2, 3, 4, 5]


In [ ]:
L1 = [0,1,2]
L2 = [3,4,5]
juncao = L1 + L2
print(juncao)


[0, 1, 2, 3, 4, 5]


In [ ]:
L = [ 3, 'abacate',9.7, [5,6,3], "Python"]
print(L[1:4]) #print da posicao 1 até 3
print (L[2:]) #3 print da posição 2 até o fim da lista
print (L[:4]) #print do inicio da lista ate a posição 3

In [ ]:
ErradicarPobreza = [ "Mendingo Praça da sé ", "carapicuiba, osasco ", "Pobreza em geral ", "pessoas com renda percapita maior que 10mil reais"]

del ErradicarPobreza[0:3]
print(ErradicarPobreza)

['pessoas com renda percapita maior que 10mil reais']


In [ ]:
precos = {"Lapis":5.5,"borracha":7.0, "caneta":6.5}

print(precos)
print(precos. keys())
print(precos. values())
print(precos["Lapis"])

del precos["borracha"]
print("caneta" in precos)
print("caderno" in precos)





dict_keys(['Lapis', 'borracha', 'caneta'])
dict_values([5.5, 7.0, 6.5])
{'Lapis': 5.5, 'borracha': 7.0, 'caneta': 6.5}
5.5
True
False


In [ ]:
animais = {"gato", "cachorro", "lobo", "gato"}
print ("peixe" in animais)
animais.add("peixe")
print ("peixe" in animais)
print(len(animais))

False
True
4


In [ ]:
tpl = (1,2,3,4,5,6)
print(tpl)

print(tpl[4])

(1, 2, 3, 4, 5, 6)
5


In [ ]:
def soma(a,b):
  c = a + b
  return c

soma(3,2)
print(soma(3,2))

5


In [ ]:
def leitura():
 nome = input("Digite seu nome:")
 sobrenome = input("Digite seu sobrenome:")
 nomeCompleto = nome + " " + sobrenome
 print ("Seu nome comple é: ",nomeCompleto )

leitura()

Digite seu nome:Jonata
Digite seu sobrenome:Garcia
Seu nome comple é:  Jonata Garcia


In [ ]:
def potencia(a,b):
 c = a ** b
 return c

X = int(input("digite um valor:"))
Y = int(input("Digite o valor de potência:"))
print(potencia(X,Y))




digite um valor:5
Digite o valor de potência:5
3125


In [ ]:
def soma(a,b):
 c = a + b
 return c

X = float(input("digite um valor:"))
Y = float(input("Digite o valor"))
print(soma(X,Y))

digite um valor:5
Digite o valor2
7.0


In [ ]:
nota = float(input("digite sua nota:"))

if nota < 7.0:
 print("REPROVADO")

else:
  print(" Parabens voce foi aprovado")

digite su nota:7
 Parabens voce foi aprovado


In [ ]:
idade = int(input("Digite sua idade:"))
if idade < 3:
 print("Bebe")
elif idade < 10:
  print("Infantil")
elif idade < 14:
  print("Adolescente")
elif idade < 30:
  print("Jovem")
elif idade < 50:
  print("adulto")
else:
  print("Idoso")

Digite sua idade:40
adulto


In [ ]:
senha = "54321"
leitura = " "

while (leitura != senha):
  leitura = input ("Digte a senha:")
  if leitura == senha: print ("Acesso liberado")
  else: print ("Senha incorreta. Tente novamente")

Digte a senha:112
Senha incorreta. Tente novamente
Digte a senha:65465814
Senha incorreta. Tente novamente
Digte a senha:54321
Acesso liberado


In [ ]:
contador = 0
somador = 0
while contador <5:
  contador = contador + 1
  valor = float(input('digite o '+str(contador)+ " Valor: "))
  somador = somador + valor
print("Soma = ", somador)

digite o 1 Valor: 1
digite o 2 Valor: 2
digite o 3 Valor: 3
digite o 4 Valor: 4
digite o 5 Valor: 50
Soma =  60.0


In [ ]:
Lista_notas=[3.4,6.6,8,9,10,99.5,8.8,4.3]
soma=0
for nota in Lista_notas:
  soma = soma+nota
média = soma+nota
print ('Média = ', média)

def CalcMedia(Lista):
  soma=0
  for nota in Lista:
    soma = soma+nota
    return soma/len(Lista)

    Lista_notas= [3.4,6.6,8,9,10,99.5,8.8,4.3]
    media = CalcMedia(Lista_notas)
    print('Méda = ', media)

Média =  153.90000000000003


In [ ]:
S=0
for x in range(1,20,3):
  S = S+x
print('Soma = ',S)

Soma =  100


In [ ]:
def categoria(idade):
  ctg = ""
  if idade <3:
   ctg = 'bebe'
  elif idade < 10:
   ctg = 'infantil'
  elif idade <18:
   ctg = 'adolecente'
  else:
   ctg ='adulto'
  return ctg

idade = int(input("Digite sua idade"))
print("A sua categoria é:",categoria(idade))


Digite sua idade21
A sua categoria é: adulto


In [1]:
def inclui(d):
  nome = input("Digite um nome para incluir no perfil: ")
  if nome in d:
    print("Nome já existe não pode ser incluído")
  else:
    fone = input("Digite o fone para incluir no perfil: ")
    d[nome]= fone

def consulta (d):
  nome = input("Digite o nome do perfil que deseja consultar: ")
  print ("telefone ",d.get(nome, 'não disponível' ))

def altera(d):
  nome = input("Digite o nome do perfil que deseja alterar o fone: ")
  print ("telefone atual: ",d.get(nome, 'não disponível'))

  if nome in d:
    fone = input ("Digite o novo fone para o perfil: ")
    d[nome]=fone
    print("Telefone alterado !")
  else:
    print("telefone não pode ser alterado!")

def exclui(d):
  nome = input("Digite o nome do perfil que deseja exclui: ")
  if nome in d:
    del d[nome]
    print("Perfil (nome e fone) excluídos!")
  else:
      print("Nome inexistente")

def monstra (d):
  print ("Agenda:")
  for nome in d.keys():
    print(nome,d[nome])

agenda = {}
inclui(agenda)
inclui(agenda)
inclui(agenda)
consulta(agenda)
altera(agenda)
exclui(agenda)
mostra(agenda)

agenda = {}
opc = 10
while opc !=0:
   opc = int(input("0 - Sair, 1 - Incluir, 2 - Consultar, 3 - Alterar, 4 Excluir,5 - Mostrar:"))
if opc == 1:
   inclui(agenda)
elif opc ==2:
   consulta(agenda)
elif opc==3:
  alterado(agenda)
elif opc == 4:
   exclui(agenda)
elif opc == 0:
  print("bye!")
else:
  print("Opções inválida !")

Digite um nome para incluir no perfil: Jonata
Digite o fone para incluir no perfil: 11 958751362
Digite um nome para incluir no perfil: Isabela
Digite o fone para incluir no perfil: 11 96365372
Digite um nome para incluir no perfil: dfolvcmlfm
Digite o fone para incluir no perfil: fçldvmçdf[
Digite o nome do perfil que deseja consultar: jonata
telefone  não disponível
Digite o nome do perfil que deseja alterar o fone: Isabela
telefone atual:  11 96365372
Digite o novo fone para o perfil: 11 7846746t736547
Telefone alterado !
Digite o nome do perfil que deseja exclui: Jpnata
Nome inexistente


NameError: name 'mostra' is not defined

In [ ]:
import numpy as np

a = np.array([12,34,26,18,10])

print(a)
print(a.dtype)


a1 = np.array([1,2,3], dtype = np.float64) # cria o array como float de 64 bits

print(a1)
print(a1.dtype)


a2 = np.array([1,2,3], dtype = np.int32)  # cria o array como float de 64 bits

print(a2)
print(a2.dtype)


a3 = np.array([1.4, 3.6, -5.1, 9.42, 4.99999999 ]) # Podemos transformar tipos de dados de arrays

print(a3)
print(a3.dtype) # Mostra array([1.4, 3.6, -5.1, 9.42, 4.999999])

a4 = a3.astype(np.int32) # quando transformamos de float para int os valores são truncados

print(a4)
print(a4.dtype)


a5 = np.array([1,2,3,4]) # Mostra array([ 1, 3, -5, 9, 4])

print(a5)
print(a5.dtype)

a6 = a5.astype(float) # podemos fazer o inverso também.

print(a6)
print(a6.dtype)
# Mostra array([1., 2., 3., 4.])


[12 34 26 18 10]
int64
[1. 2. 3.]
float64
[1 2 3]
int32
[ 1.4         3.6        -5.1         9.42        4.99999999]
float64
[ 1  3 -5  9  4]
int32
[1 2 3 4]
int64
[1. 2. 3. 4.]
float64


In [ ]:
b = np.array([[7,2,23],[12,27,4],[5,34,23]])
# cria um matriz bidimensional
print(b)

import numpy as np
c = np.empty([3,2], dtype = int)
print (c)

d = np.zeros([4,3])
# cria uma matriz 4x3 com valores zero
print(d)

e = np.ones([5,7])
# cria uma matriz de 5x7 com valores 1
print(e)

f = np.eye(5)
# cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero
print(f)

g2= np.random.randn((5))
print(g2)

h = np.floor(10*np.random.random((3,4)))
print(h)
h = (10*np.random.random((3,4)))
print(h)
h = np.floor(h)
print(h)

gnr = np.random.default_rng(0)
i = gnr.random(3)
print (i)

i = gnr.integers(10, size=(3, 4))
print(i)

j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

k = np.array([[17,22,43],[27,25,14],[15,24,32]])
# cria a matriz bidimensional k
print(k)
# Mostra a matriz k
print(k[0][1])
# Mostra um elemento específico da matriz k
print(k.shape)
# Mostra o tamanho das dimensões da matriz k
print(k.max())
# Mostra o maior valor da matriz k
print(k.min())
# Mostra o menor valor da matriz k
print((k.sum()))
# Mostra a soma dos valores da matriz k
print(k.mean())
# Mostra o valor da média dos valores da matriz k
print(k.std())

k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))
# Mostra o valor da raiz quadrada de todos elementos
print(np.exp(k1))
# Mostra o valor do exponencial de todos elementos




[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]
[[ 95501028866456               0]
 [132338713334320 132338385183152]
 [132338385183216 132338385183280]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[-0.41010105 -1.22950552  0.60258487 -0.38636955  1.38761621]
[[1. 4. 2. 9.]
 [7. 3. 2. 0.]
 [6. 9. 8. 8.]]
[[0.51687249 5.37273014 8.94847604 7.38607177]
 [0.03483012 2.92636578 7.85699505 4.68529309]
 [3.02066631 3.86244647 7.29197384 1.60920166]]
[[0. 5. 8. 7.]
 [0. 2. 7. 4.]
 [3. 3. 7. 1.]]
[0.63696169 0.26978671 0.04097352]
[[0 0 1 8]
 [6 9 5 6]
 [9 7 6 5]]
[11 12 13 14 15 16 17 18 19 20]
[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)
43
14
219
24.333333333333332
8.615231988880057
[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.311231

In [ ]:
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
l_linha_1 = l[0, :]
print(l_linha_1)
l_linha_2 = l[1, :]
print(l_linha_2)
l_linha_3 = l[2, :]
print(l_linha_3)
l_coluna_1 = l[:, 0]
print(l_coluna_1)
l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
[4 5]
[6 1]
[7 4]
[4 6 7]
[5 1 4]


In [ ]:
m = np.array([1, 2, 3, 4, 5, 6])
print(m[1])
# Mostra o elemento da posição 2
print(m[0:2])
# Mostra o array criado a partir da posição 0, dois elementos
print(m[1:])
# Mostra o array criado a partir da 2a posição
# até todo o restante do array
print(m[-3:])
# Mostra o array criado a partir da antepenúltima
#posição até o final

2
[1 2]
[2 3 4 5 6]
[4 5 6]


In [ ]:
n = np.array([[1, 2], [3, 4]])

o = np.array([[1, 1], [1, 1]])
res1 = n+o
print(res1)
res2 = n*o
print(res2)

In [ ]:
r = np.arange(15).reshape((3, 5))
# rearranja um conjunto de 15 elementos de 0 a 14 em 3 linhas e 5 colunas.
print(r)
# mostra a matrizes transposta entre linha e coluna
s = r.T
print(s)

SyntaxError: ignored

In [ ]:
r = np.arange(15).reshape((3, 5))
# rearranja um conjunto de 15 elementos de 0 a 14 em 3 linhas e 5 colunas.
print(r)
# mostra a matrizes transposta entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [ ]:
t = np.arange(16).reshape((2, 2, 4))
print(t)
u = t.swapaxes(1, 2)
print(u)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [ ]:
v = np.random.randn(4, 4)
print(v)
# criando matriz com valores aleatórios positivos e negativos
x = (v > 0)
# criando matriz com valores booleanos baseado no array v
print(x)
z = np.where(x > 0, 1, -1)
# criando matriz com valores -1 e 1 baseado nos valores do array x
print(z)

[[-1.58415831e+00  1.16442730e+00 -8.61258476e-01  8.40058533e-04]
 [-7.62006301e-02  4.91391452e-01 -2.96706592e-01 -5.49331446e-01]
 [-1.18140690e+00  2.15711472e+00 -7.35816384e-01  1.37050777e+00]
 [-3.29404097e-01 -4.91273434e-01 -1.06418973e+00 -1.71523920e-02]]
[[False  True False  True]
 [False  True False False]
 [False  True False  True]
 [False False False False]]
[[-1  1 -1  1]
 [-1  1 -1 -1]
 [-1  1 -1  1]
 [-1 -1 -1 -1]]
